export const TOOL_ENDPOINT_CONTRACTS: Readonly<Record<string, readonly string[]>> = Object.freeze({
  n8n_workflows_list: ["GET /workflows"],
  n8n_workflows_get: ["GET /workflows/{workflowId}"],
  n8n_workflows_create: ["POST /workflows"],
  n8n_workflows_update: ["GET /workflows/{workflowId}", "PUT /workflows/{workflowId}"],
  n8n_update_node: ["GET /workflows/{workflowId}", "PUT /workflows/{workflowId}"],
  n8n_workflows_delete: ["DELETE /workflows/{workflowId}"],
  n8n_workflows_activate: ["POST /workflows/{workflowId}/activate"],
  n8n_workflows_deactivate: ["POST /workflows/{workflowId}/deactivate"],
  n8n_workflows_get_version: ["GET /workflows/{workflowId}/{versionId}"],
  n8n_workflows_get_tags: ["GET /workflows/{workflowId}/tags"],
  n8n_workflows_update_tags: ["PUT /workflows/{workflowId}/tags"],
  n8n_workflows_archive: ["POST /workflows/{workflowId}/archive"],
  n8n_workflows_unarchive: ["POST /workflows/{workflowId}/unarchive"],
  n8n_workflows_diff: [
    "GET /workflows/{workflowId}/{versionId}",
    "GET /workflows/{workflowId}?excludePinnedData=true",
  ],
  n8n_executions_list: ["GET /executions"],
  n8n_executions_get: ["GET /executions/{executionId}"],
  n8n_executions_delete: ["DELETE /executions/{executionId}"],
  n8n_executions_retry: ["POST /executions/{executionId}/retry"],
  n8n_executions_stop: ["POST /executions/{executionId}/stop"],
  n8n_credentials_create: ["POST /credentials"],
  n8n_credentials_delete: ["DELETE /credentials/{credentialId}"],
  n8n_credentials_schema: ["GET /credentials/schema/{credentialType}"],
  n8n_credentials_list: ["GET /credentials"],
  n8n_credentials_get: ["GET /credentials/{credentialId}"],
  n8n_credentials_update: ["PATCH /credentials/{credentialId}"],
  n8n_credentials_test: ["POST /credentials/{credentialId}/test"],
  n8n_credentials_usage: ["GET /workflows?excludePinnedData=true"],
  n8n_tags_list: ["GET /tags"],
  n8n_tags_get: ["GET /tags/{tagId}"],
  n8n_tags_create: ["POST /tags"],
  n8n_tags_update: ["PUT /tags/{tagId}"],
  n8n_tags_delete: ["DELETE /tags/{tagId}"],
  n8n_users_list: ["GET /users"],
  n8n_users_get: ["GET /users/{id-or-email}"],
  n8n_users_create: ["POST /users"],
  n8n_users_delete: ["DELETE /users/{userId}"],
  n8n_health: ["GET /healthz"],
  n8n_insights_summary: ["GET /insights/summary"],
  n8n_audit_generate: ["POST /audit"],
  n8n_search_workflows: ["GET /workflows?excludePinnedData=true"],
  n8n_get_node_docs: [],
  n8n_list_node_types: ["GET /workflows?excludePinnedData=true"],
  n8n_introspect: [
    "GET /workflows/{workflowId}?excludePinnedData=true",
    "GET /executions",
    "GET /executions/{executionId}?redactExecutionData=true",
  ],
  n8n_community_packages_list: ["GET /community-packages"],
});
